# Generated by Django 4.1.5 on 2023-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_app', '0003_alter_sentimentmodel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentmodel',
            name='review',
            field=models.TextField(max_length=5000),
        ),
    ]
